### ISSUE TITLE
Looking for corn_review.txt data

### ISSUE THREAD

**Issue by ClaudeCoulombe** [Apress/building-an-enterprise-chatbot#1]
Greetings, 

I'm looking for the original corn_review.txt  data file.

Thanks

Claude

P.-S.: I've created one below but it necessary gave results that are pretty different than yours.

"I consume about a jar every two weeks of this, either adding it to fajitas or using it as a corn chip dip"
"As soon as I tasted one and it tasted like a corn chip I checked the ingredients"
"I found these crisps at our local WalMart & figured I would give them a try"
"To taste as a chip based on corn"
" What about the new ginger flavor corn syrup?"
"They have a big selection of flavored corn chips, among them a ginger flavor corn syrup"

**Comment by karthy1988** [comment]
[corn_review.txt](https://github.com/Apress/building-an-enterprise-chatbot/files/4642579/corn_review.txt)

Hi Claude,

Thanks for reaching out. PFA the requested dataset.

Regards,
Karthik

**Comment by ClaudeCoulombe** [comment]
Greetings Abhishek and Karthik,

Thanks a lot for the quick answer and the data!

The code works very well but the results are a bit different.
It's probably in part related to the version of f the Gensim library used, mine is 3.8.1  
But I also note that probably a part is caused by the intrinsic random nature of the algorithm since the results vary from one execution to another.

Keep up the good work!

Claude


Le lun. 18 mai 2020, à 08 h 19, Abhishek Singh <notifications@github.com> a
écrit :
