### ISSUE TITLE
Looking for neg / pos reviews corpus data

### ISSUE THREAD

**Issue by ClaudeCoulombe** [Apress/building-an-enterprise-chatbot#2]
Greetings folks,

I'm looking for the original neg / pos reviews corpus data?

Thanks

Claude

**Comment by karthy1988** [comment]
[corpus.zip](https://github.com/Apress/building-an-enterprise-chatbot/files/4642633/corpus.zip)

Hi Claude,

PFA the requested data. We will update the same in the repo shortly.

Regards,
Karthik

**Comment by ClaudeCoulombe** [comment]
Greetings,

Thanks a lot for the quick answer and the data!
The code works very well and identically to your book.

Claude

**Comment by ClaudeCoulombe** [comment]
Greetings Abhishek and Karthik,

Thanks a lot for the quick answer and the data!
The code works very well and identically to your book.

As normal, I've found some small errors in your nice book, how and where
can I share it with you?

Claude

Le lun. 18 mai 2020, à 08 h 19, Abhishek Singh <notifications@github.com> a
écrit :

**Comment by karthy1988** [comment]
Hi Claude,

I really appreciate your feedback. You can send the error to karthy1988@gmail.com. We will do our best to address the same.

Regards,
Karthik
